version: "3.4"
services:
  csharp: #docker run -it -v ${PWD}:/ -w /work -p 5000:5000 learn /bin/sh
    container_name: learn
    image: learn
    build:
      context: .
      target: build-env
    volumes:
    - ./:/work/
    ports:
      - 5000:5000
